name: infraplan
description: "Gerenciador de Infraestrutura de Redes com suporte KMZ/KML"
publish_to: 'none'
version: 0.0.2+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Mapas
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^1.3.6
  # Localização
  geolocator: ^10.0.0
  # KMZ/KML
  xml: ^6.5.0
  archive: ^3.6.1
  # Armazenamento
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3+1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.3
  # Utilidades
  uuid: ^4.5.1
  file_picker: ^8.1.4
  share_plus: ^10.0.3
  permission_handler: ^11.1.0
  # Conectividade
  connectivity_plus: ^6.0.0
  # UI
  flutter_colorpicker: ^1.1.0
  provider: ^6.1.2
  fl_chart: ^0.69.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
